// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260116141744_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.MedicalRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DoctorID")
                        .HasColumnType("int");

                    b.Property<int>("PatientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RecordID");

                    b.HasIndex("DoctorID");

                    b.HasIndex("PatientID");

                    b.ToTable("tblMedicalRecords");

                    b.HasData(
                        new
                        {
                            RecordID = 1,
                            DateCreated = new DateTime(2025, 12, 20, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "",
                            DoctorID = 2,
                            PatientID = 1,
                            Status = "Waiting",
                            Symptoms = "Đau bụng dữ dội, buồn nôn",
                            TotalAmount = 0m
                        },
                        new
                        {
                            RecordID = 2,
                            DateCreated = new DateTime(2025, 12, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Viêm họng cấp",
                            DoctorID = 2,
                            PatientID = 2,
                            Status = "Finished",
                            Symptoms = "Ho khan, sốt nhẹ",
                            TotalAmount = 0m
                        },
                        new
                        {
                            RecordID = 3,
                            DateCreated = new DateTime(2025, 12, 19, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Diagnosis = "Viêm da cơ địa",
                            DoctorID = 2,
                            PatientID = 3,
                            Status = "Paid",
                            Symptoms = "Dị ứng da",
                            TotalAmount = 150000m
                        });
                });

            modelBuilder.Entity("Entities.Medicine", b =>
                {
                    b.Property<int>("MedicineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicineID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ImportPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MedicineID");

                    b.HasIndex("CategoryID");

                    b.ToTable("tblMedicines");

                    b.HasData(
                        new
                        {
                            MedicineID = 1,
                            CategoryID = 2,
                            ExpiryDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 1000m,
                            MedicineName = "Panadol Extra",
                            SellPrice = 2500m,
                            StockQuantity = 500,
                            Unit = "Viên"
                        },
                        new
                        {
                            MedicineID = 2,
                            CategoryID = 1,
                            ExpiryDate = new DateTime(2025, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 15000m,
                            MedicineName = "Amoxicillin 500mg",
                            SellPrice = 25000m,
                            StockQuantity = 100,
                            Unit = "Vỉ"
                        },
                        new
                        {
                            MedicineID = 3,
                            CategoryID = 3,
                            ExpiryDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 45000m,
                            MedicineName = "Vitamin C 1000mg",
                            SellPrice = 60000m,
                            StockQuantity = 50,
                            Unit = "Hộp"
                        },
                        new
                        {
                            MedicineID = 4,
                            CategoryID = 1,
                            ExpiryDate = new DateTime(2027, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 10000m,
                            MedicineName = "Berberin",
                            SellPrice = 18000m,
                            StockQuantity = 200,
                            Unit = "Lọ"
                        });
                });

            modelBuilder.Entity("Entities.MedicineCategory", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryID");

                    b.ToTable("tblMedicineCategories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Kháng sinh"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Giảm đau & Hạ sốt"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Vitamin & Khoáng chất"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Tim mạch & Huyết áp"
                        });
                });

            modelBuilder.Entity("Entities.Patient", b =>
                {
                    b.Property<int>("PatientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PatientID");

                    b.ToTable("tblPatients");

                    b.HasData(
                        new
                        {
                            PatientID = 1,
                            Address = "Hà Nội",
                            BirthYear = 1990,
                            FullName = "Nguyễn Văn A",
                            Gender = "Nam",
                            Phone = "0987654321"
                        },
                        new
                        {
                            PatientID = 2,
                            Address = "Đà Nẵng",
                            BirthYear = 1995,
                            FullName = "Trần Thị B",
                            Gender = "Nữ",
                            Phone = "0123456789"
                        },
                        new
                        {
                            PatientID = 3,
                            Address = "TP.HCM",
                            BirthYear = 1985,
                            FullName = "Lê Văn C",
                            Gender = "Nam",
                            Phone = "0999888777"
                        });
                });

            modelBuilder.Entity("Entities.PrescriptionDetail", b =>
                {
                    b.Property<int>("DetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetailID"));

                    b.Property<int?>("MedicalRecordRecordID")
                        .HasColumnType("int");

                    b.Property<int>("MedicineID")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DetailID");

                    b.HasIndex("MedicalRecordRecordID");

                    b.HasIndex("MedicineID");

                    b.HasIndex("RecordID");

                    b.ToTable("tblPrescriptionDetails");
                });

            modelBuilder.Entity("Entities.RecordService", b =>
                {
                    b.Property<int>("RecordServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordServiceID"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RecordID")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("RecordServiceID");

                    b.HasIndex("RecordID");

                    b.HasIndex("ServiceID");

                    b.ToTable("tblRecordService");

                    b.HasData(
                        new
                        {
                            RecordServiceID = 1,
                            Price = 100000m,
                            Quantity = 1,
                            RecordID = 2,
                            ServiceID = 1
                        });
                });

            modelBuilder.Entity("Entities.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("tblRoles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Bác sĩ"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Nhân viên"
                        });
                });

            modelBuilder.Entity("Entities.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceID");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceID = 1,
                            Price = 100000m,
                            ServiceName = "Khám thường"
                        },
                        new
                        {
                            ServiceID = 2,
                            Price = 300000m,
                            ServiceName = "Khám VIP"
                        },
                        new
                        {
                            ServiceID = 3,
                            Price = 150000m,
                            ServiceName = "Siêu âm"
                        });
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.ToTable("tblUsers");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            FullName = "Quản Trị Viên",
                            IsActive = true,
                            Password = "123",
                            RoleID = 1,
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            FullName = "Bác sĩ CK1",
                            IsActive = true,
                            Password = "123",
                            RoleID = 2,
                            UserName = "bacsi"
                        });
                });

            modelBuilder.Entity("Entities.MedicalRecord", b =>
                {
                    b.HasOne("Entities.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PatientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Entities.Medicine", b =>
                {
                    b.HasOne("Entities.MedicineCategory", "Category")
                        .WithMany("Medicines")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Entities.PrescriptionDetail", b =>
                {
                    b.HasOne("Entities.MedicalRecord", null)
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("MedicalRecordRecordID");

                    b.HasOne("Entities.Medicine", "Medicine")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("MedicineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.MedicalRecord", "MedicalRecord")
                        .WithMany()
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("Entities.RecordService", b =>
                {
                    b.HasOne("Entities.MedicalRecord", "MedicalRecord")
                        .WithMany("RecordServices")
                        .HasForeignKey("RecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalRecord");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Entities.User", b =>
                {
                    b.HasOne("Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Entities.MedicalRecord", b =>
                {
                    b.Navigation("PrescriptionDetails");

                    b.Navigation("RecordServices");
                });

            modelBuilder.Entity("Entities.Medicine", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("Entities.MedicineCategory", b =>
                {
                    b.Navigation("Medicines");
                });

            modelBuilder.Entity("Entities.Patient", b =>
                {
                    b.Navigation("MedicalRecords");
                });

            modelBuilder.Entity("Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
